### ISSUE TITLE
Error on 64-bit android phone.

### ISSUE THREAD

**Issue by zhoukekestar** [zhoukekestar/weex-quick-start#1]
Error on 64-bit android phone.
`java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.github.zhoukekestar.weexquickstart/files/libweexcorebk1.so" is 32-bit instead of 64-bit`

**Comment by zhoukekestar** [comment]
Fixed: 
When dependencies has `compile 'com.facebook.fresco:fresco:0.10.0'` on build.gradle.
Error occured: 

``` bash
10-21 15:04:49.012 3477-3477/? I/art: Late-enabling -Xcheck:jni
10-21 15:04:49.039 3477-3477/? D/TidaProvider: TidaProvider()
10-21 15:04:49.061 3477-3477/com.github.zhoukekestar.myapplication V/SettingsInterface: invalidate [system]: current 6179 != cached 0
10-21 15:04:49.062 3477-3477/com.github.zhoukekestar.myapplication D/ActivityThread: hoder:android.app.IActivityManager$ContentProviderHolder@2b3856f,provider,holder.Provider:android.content.ContentProviderProxy@3bf1d27c
10-21 15:04:49.086 3477-3477/com.github.zhoukekestar.myapplication I/InstantRun: Instant Run Runtime started. Android package is com.github.zhoukekestar.myapplication, real application class is com.github.zhoukekestar.myapplication.MainApplication.
10-21 15:04:49.180 3477-3477/com.github.zhoukekestar.myapplication E/weex: launchInspector HackAssertionException com.taobao.weex.utils.WXHack$HackDeclaration$HackAssertionException: java.lang.ClassNotFoundException: com.taobao.weex.devtools.debug.DebugServerProxy
                                                                               at com.taobao.weex.utils.WXHack.into(WXHack.java:232)
                                                                               at com.taobao.weex.bridge.WXBridgeManager.launchInspector(WXBridgeManager.java:359)
                                                                               at com.taobao.weex.bridge.WXBridgeManager.<init>(WXBridgeManager.java:334)
                                                                               at com.taobao.weex.bridge.WXBridgeManager.getInstance(WXBridgeManager.java:346)
                                                                               at com.taobao.weex.WXSDKEngine.doInitInternal(WXSDKEngine.java:222)
                                                                               at com.taobao.weex.WXSDKEngine.initialize(WXSDKEngine.java:211)
                                                                               at com.github.zhoukekestar.myapplication.MainApplication.onCreate(MainApplication.java:19)
                                                                               at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
                                                                               at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1016)
                                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4762)
                                                                               at android.app.ActivityThread.access$1500(ActivityThread.java:169)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                               at android.os.Looper.loop(Looper.java:194)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                                                                            Caused by: java.lang.ClassNotFoundException: com.taobao.weex.devtools.debug.DebugServerProxy
                                                                               at java.lang.Class.classForName(Native Method)
                                                                               at java.lang.Class.forName(Class.java:308)
                                                                               at java.lang.Class.forName(Class.java:272)
                                                                               at com.taobao.weex.utils.WXHack.into(WXHack.java:230)
                                                                               at com.taobao.weex.bridge.WXBridgeManager.launchInspector(WXBridgeManager.java:359) 
                                                                               at com.taobao.weex.bridge.WXBridgeManager.<init>(WXBridgeManager.java:334) 
                                                                               at com.taobao.weex.bridge.WXBridgeManager.getInstance(WXBridgeManager.java:346) 
                                                                               at com.taobao.weex.WXSDKEngine.doInitInternal(WXSDKEngine.java:222) 
                                                                               at com.taobao.weex.WXSDKEngine.initialize(WXSDKEngine.java:211) 
                                                                               at com.github.zhoukekestar.myapplication.MainApplication.onCreate(MainApplication.java:19) 
                                                                               at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370) 
                                                                               at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1016) 
                                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4762) 
                                                                               at android.app.ActivityThread.access$1500(ActivityThread.java:169) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                               at android.os.Looper.loop(Looper.java:194) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5546) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) 
                                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "com.taobao.weex.devtools.debug.DebugServerProxy" on path: DexPathList[[dex file "/data/data/com.github.zhoukekestar.myapplication/files/instant-run/dex/slice-support-annotations-23.3.0_f7486936d20fe5cecace9f191cb695dc35bd15ff-classes.dex", dex file "/data/data/com.github.zhoukekestar.myapplication/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.github.zhoukekestar.myapplication/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.github.zhoukekestar.myapplication/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.github.zhoukekestar.myapplication/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.github.zhoukekestar.myapplication/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.github.zhoukekestar.myapplication/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.github.zhoukekestar.myapplication/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.github.zhoukekestar.myapplication/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.github.zhoukekestar.myapplication/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.github.zhoukekestar.myapplication/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.github.zhoukekestar.myapplication/files/instant-run/dex/slice-picasso-2.5.2_2428dbd5eabf65ae69bc01abd6e4b72d08e545aa-classes.dex", dex file "/data/data/com.github.zhoukekestar.myapplication/files/instant-run/dex/slice-library-2.4.0_dd460f45d27a359687729c3c169358b1eda3100b-classes.dex", dex file "/data/data/com.github.zhoukekestar.myapplication/files/instant-run/dex/slice-internal_impl-23.3.0_7103178cb1f2b2094664db4c639ed87cbd7ddde2-classes.dex", dex file "/data/data/com.github.zhoukekestar.myapplication/files/instant-run/dex/slice-fastjson-1.1.46.android_69981fb0d540ff52e7f22557c093fa18eeea1bd1-classes.dex", dex file "/data/data/com.github.zhoukekestar.myapplication/files/instant-run/dex/slice-com.taobao.android-weex_sdk-0.8.0.1_b89fbe680ee68564f4c12977b64a40a612979fec-classes.dex", dex file "/data/data/com.github.z
10-21 15:04:49.194 3477-3512/com.github.zhoukekestar.myapplication E/art: dlopen("/data/data/com.github.zhoukekestar.myapplication/files/libweexv8bk1.so", RTLD_LAZY) failed: dlopen failed: "/data/data/com.github.zhoukekestar.myapplication/files/libweexv8bk1.so" is 32-bit instead of 64-bit
10-21 15:04:49.196 3477-3512/com.github.zhoukekestar.myapplication E/weex: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.github.zhoukekestar.myapplication/files/libweexv8bk1.so" is 32-bit instead of 64-bit
                                                                               at java.lang.Runtime.load(Runtime.java:331)
                                                                               at java.lang.System.load(System.java:982)
                                                                               at com.taobao.weex.utils.WXSoInstallMgrSdk._loadUnzipSo(WXSoInstallMgrSdk.java:441)
                                                                               at com.taobao.weex.utils.WXSoInstallMgrSdk.initSo(WXSoInstallMgrSdk.java:311)
                                                                               at com.taobao.weex.WXSDKEngine$1.run(WXSDKEngine.java:238)
                                                                               at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:234)
                                                                               at android.os.Handler.handleCallback(Handler.java:815)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                               at android.os.Looper.loop(Looper.java:194)
                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
10-21 15:04:49.229 3477-3477/com.github.zhoukekestar.myapplication D/weex_perf: [render time]SDKInitInvokeTime:69
10-21 15:04:49.229 3477-3477/com.github.zhoukekestar.myapplication V/ActivityThread: Handling launch of ActivityRecord{d22035a token=android.os.BinderProxy@261d098b {com.github.zhoukekestar.myapplication/com.github.zhoukekestar.myapplication.MainActivity}}
10-21 15:04:49.327 3477-3477/com.github.zhoukekestar.myapplication V/ActivityThread: ActivityRecord{d22035a token=android.os.BinderProxy@261d098b {com.github.zhoukekestar.myapplication/com.github.zhoukekestar.myapplication.MainActivity}}: app=com.github.zhoukekestar.myapplication.MainApplication@d789e81, appName=com.github.zhoukekestar.myapplication, pkg=com.github.zhoukekestar.myapplication, comp={com.github.zhoukekestar.myapplication/com.github.zhoukekestar.myapplication.MainActivity}, dir=/data/app/com.github.zhoukekestar.myapplication-1/base.apk
10-21 15:04:49.369 3477-3512/com.github.zhoukekestar.myapplication E/art: dlopen("/data/data/com.github.zhoukekestar.myapplication/files/libweexv8bk1.so", RTLD_LAZY) failed: dlopen failed: "/data/data/com.github.zhoukekestar.myapplication/files/libweexv8bk1.so" is 32-bit instead of 64-bit
10-21 15:04:49.369 3477-3512/com.github.zhoukekestar.myapplication E/weex: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.github.zhoukekestar.myapplication/files/libweexv8bk1.so" is 32-bit instead of 64-bit
                                                                               at java.lang.Runtime.load(Runtime.java:331)
                                                                               at java.lang.System.load(System.java:982)
                                                                               at com.taobao.weex.utils.WXSoInstallMgrSdk._loadUnzipSo(WXSoInstallMgrSdk.java:441)
                                                                               at com.taobao.weex.utils.WXSoInstallMgrSdk.unZipSelectedFiles(WXSoInstallMgrSdk.java:532)
                                                                               at com.taobao.weex.utils.WXSoInstallMgrSdk.initSo(WXSoInstallMgrSdk.java:325)
                                                                               at com.taobao.weex.WXSDKEngine$1.run(WXSDKEngine.java:238)
                                                                               at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:234)
                                                                               at android.os.Handler.handleCallback(Handler.java:815)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                               at android.os.Looper.loop(Looper.java:194)
                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
10-21 15:04:49.372 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXText
10-21 15:04:49.376 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.376 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXDiv
10-21 15:04:49.379 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.380 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXDiv
10-21 15:04:49.381 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.381 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXDiv
10-21 15:04:49.383 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.383 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXDiv
10-21 15:04:49.385 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.385 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXImage
10-21 15:04:49.389 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.389 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXImage
10-21 15:04:49.392 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.392 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXScroller
10-21 15:04:49.398 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.399 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXSlider
10-21 15:04:49.402 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.402 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.403 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXListComponent
10-21 15:04:49.408 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.409 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXListComponent
10-21 15:04:49.411 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.412 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:HorizontalListComponent
10-21 15:04:49.414 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.414 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXCell
10-21 15:04:49.416 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.416 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXIndicator
10-21 15:04:49.418 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.419 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXVideo
10-21 15:04:49.421 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.421 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXInput
10-21 15:04:49.425 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.425 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.425 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXSwitch
10-21 15:04:49.427 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.427 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXA
10-21 15:04:49.429 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.429 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXEmbed
10-21 15:04:49.432 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.432 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXWeb
10-21 15:04:49.434 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.434 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXRefresh
10-21 15:04:49.436 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.437 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXLoading
10-21 15:04:49.439 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.439 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXLoadingIndicator
10-21 15:04:49.441 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.441 3477-3512/com.github.zhoukekestar.myapplication D/SimpleComponentHolder: Generate Component:WXHeader
10-21 15:04:49.443 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.443 3477-3512/com.github.zhoukekestar.myapplication D/TypeModuleFactory: extractMethodNames:WXModalUIModule
10-21 15:04:49.446 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.447 3477-3512/com.github.zhoukekestar.myapplication D/TypeModuleFactory: extractMethodNames:WXInstanceWrap
10-21 15:04:49.447 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.448 3477-3512/com.github.zhoukekestar.myapplication D/TypeModuleFactory: extractMethodNames:WXAnimationModule
10-21 15:04:49.449 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.449 3477-3512/com.github.zhoukekestar.myapplication D/TypeModuleFactory: extractMethodNames:WXWebViewModule
10-21 15:04:49.450 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.451 3477-3512/com.github.zhoukekestar.myapplication D/TypeModuleFactory: extractMethodNames:WXNavigatorModule
10-21 15:04:49.453 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.454 3477-3512/com.github.zhoukekestar.myapplication D/TypeModuleFactory: extractMethodNames:WXStreamModule
10-21 15:04:49.455 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.455 3477-3512/com.github.zhoukekestar.myapplication D/TypeModuleFactory: extractMethodNames:WXTimerModule
10-21 15:04:49.456 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.457 3477-3512/com.github.zhoukekestar.myapplication D/TypeModuleFactory: extractMethodNames:WXStorageModule
10-21 15:04:49.459 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.459 3477-3512/com.github.zhoukekestar.myapplication D/TypeModuleFactory: extractMethodNames:WXClipboardModule
10-21 15:04:49.460 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.460 3477-3512/com.github.zhoukekestar.myapplication D/TypeModuleFactory: extractMethodNames:WXGlobalEventModule
10-21 15:04:49.461 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
10-21 15:04:49.462 3477-3477/com.github.zhoukekestar.myapplication D/ColorDrawable: setColor color = -12627531, ColorDrawable = android.graphics.drawable.ColorDrawable@25b6a85f
10-21 15:04:49.476 3477-3477/com.github.zhoukekestar.myapplication W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
10-21 15:04:49.541 3477-3477/com.github.zhoukekestar.myapplication D/ColorDrawable: setColor color = -1118482, ColorDrawable = android.graphics.drawable.ColorDrawable@23c03edc
10-21 15:04:49.570 3477-3512/com.github.zhoukekestar.myapplication D/weex: weex JS framework from assets
10-21 15:04:49.571 3477-3477/com.github.zhoukekestar.myapplication V/ActivityThread: Performing resume of ActivityRecord{d22035a token=android.os.BinderProxy@261d098b {com.github.zhoukekestar.myapplication/com.github.zhoukekestar.myapplication.MainActivity}}
10-21 15:04:49.579 3477-3512/com.github.zhoukekestar.myapplication E/art: No implementation found for int com.taobao.weex.bridge.WXBridge.initFramework(java.lang.String, com.taobao.weex.bridge.WXParams) (tried Java_com_taobao_weex_bridge_WXBridge_initFramework and Java_com_taobao_weex_bridge_WXBridge_initFramework__Ljava_lang_String_2Lcom_taobao_weex_bridge_WXParams_2)
10-21 15:04:49.581 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeInitFramework java.lang.UnsatisfiedLinkError: No implementation found for int com.taobao.weex.bridge.WXBridge.initFramework(java.lang.String, com.taobao.weex.bridge.WXParams) (tried Java_com_taobao_weex_bridge_WXBridge_initFramework and Java_com_taobao_weex_bridge_WXBridge_initFramework__Ljava_lang_String_2Lcom_taobao_weex_bridge_WXParams_2)
                                                                               at com.taobao.weex.bridge.WXBridge.initFramework(Native Method)
                                                                               at com.taobao.weex.bridge.WXBridgeManager.initFramework(WXBridgeManager.java:1033)
                                                                               at com.taobao.weex.bridge.WXBridgeManager.invokeCreateInstance(WXBridgeManager.java:832)
                                                                               at com.taobao.weex.bridge.WXBridgeManager.access$200(WXBridgeManager.java:273)
                                                                               at com.taobao.weex.bridge.WXBridgeManager$5.run(WXBridgeManager.java:813)
                                                                               at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:234)
                                                                               at android.os.Handler.handleCallback(Handler.java:815)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                               at android.os.Looper.loop(Looper.java:194)
                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
10-21 15:04:49.581 3477-3512/com.github.zhoukekestar.myapplication E/weex: [WXBridgeManager] invokeCreateInstance: framework.js uninitialized.
10-21 15:04:49.594 3477-3477/com.github.zhoukekestar.myapplication D/ActivityThread: ACT-AM_ON_RESUME_CALLED ActivityRecord{d22035a token=android.os.BinderProxy@261d098b {com.github.zhoukekestar.myapplication/com.github.zhoukekestar.myapplication.MainActivity}}
10-21 15:04:49.594 3477-3477/com.github.zhoukekestar.myapplication V/PhoneWindow: DecorView setVisiblity: visibility = 4 ,Parent =null, this =com.android.internal.policy.impl.PhoneWindow$DecorView{2421cef3 I.E..... R.....ID 0,0-0,0}
10-21 15:04:49.594 3477-3477/com.github.zhoukekestar.myapplication V/ActivityThread: Resume ActivityRecord{d22035a token=android.os.BinderProxy@261d098b {com.github.zhoukekestar.myapplication/com.github.zhoukekestar.myapplication.MainActivity}} started activity: false, hideForNow: false, finished: false
10-21 15:04:49.600 3477-3518/com.github.zhoukekestar.myapplication D/OpenGLRenderer: initialize DisplayEventReceiver 0x55b6e6d640
10-21 15:04:49.600 3477-3518/com.github.zhoukekestar.myapplication D/OpenGLRenderer: Render dirty regions requested: false
10-21 15:04:49.605 3477-3477/com.github.zhoukekestar.myapplication V/ActivityThread: Resuming ActivityRecord{d22035a token=android.os.BinderProxy@261d098b {com.github.zhoukekestar.myapplication/com.github.zhoukekestar.myapplication.MainActivity}} with isForward=true
10-21 15:04:49.605 3477-3477/com.github.zhoukekestar.myapplication V/PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{aa4c29d com.github.zhoukekestar.myapplication/com.github.zhoukekestar.myapplication.MainActivity,ident = 0}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{2421cef3 V.E..... R.....ID 0,0-0,0}
10-21 15:04:49.605 3477-3477/com.github.zhoukekestar.myapplication V/ActivityThread: Scheduling idle handler for ActivityRecord{d22035a token=android.os.BinderProxy@261d098b {com.github.zhoukekestar.myapplication/com.github.zhoukekestar.myapplication.MainActivity}}
10-21 15:04:49.606 3477-3477/com.github.zhoukekestar.myapplication D/ActivityThreadInjector: clearCachedDrawables.
10-21 15:04:49.606 3477-3477/com.github.zhoukekestar.myapplication V/MainActivity: onException errCode:wx_create_instance_error msg:createInstance fail!
10-21 15:04:49.637 3477-3477/com.github.zhoukekestar.myapplication D/ColorDrawable: setColor color = -13615201, ColorDrawable = android.graphics.drawable.ColorDrawable@31661e5e
10-21 15:04:49.646 3477-3518/com.github.zhoukekestar.myapplication D/IMGSRV: gralloc_module_getimplementationformat:2526: usage=0x1000 > fmt=0x1
10-21 15:04:49.646 3477-3518/com.github.zhoukekestar.myapplication D/IMGSRV: gralloc_module_getimplementationformat:2526: usage=0x1000 > fmt=0x1
10-21 15:04:49.646 3477-3518/com.github.zhoukekestar.myapplication D/IMGSRV: gralloc_module_getimplementationformat:2526: usage=0x1000 > fmt=0x1
10-21 15:04:49.646 3477-3518/com.github.zhoukekestar.myapplication D/IMGSRV: gralloc_module_getimplementationformat:2526: usage=0x1000 > fmt=0x1
10-21 15:04:49.646 3477-3518/com.github.zhoukekestar.myapplication D/IMGSRV: gralloc_module_getimplementationformat:2526: usage=0x1000 > fmt=0x1
10-21 15:04:49.651 3477-3518/com.github.zhoukekestar.myapplication I/OpenGLRenderer: Initialized EGL, version 1.4
10-21 15:04:49.657 3477-3518/com.github.zhoukekestar.myapplication D/OpenGLRenderer: Enabling debug mode 0
10-21 15:04:49.665 3477-3518/com.github.zhoukekestar.myapplication D/IMGSRV: gralloc_register_buffer:1390: hnd=0x55b6ea8c80 ID=3451636 fd=56 ref=1
10-21 15:04:49.665 3477-3518/com.github.zhoukekestar.myapplication D/GraphicBuffer: register, handle(0x55b6ea8c80) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
10-21 15:04:49.718 3477-3477/com.github.zhoukekestar.myapplication V/InputMethodManager: onWindowFocus: null softInputMode=288 first=true flags=#81810100
10-21 15:04:49.718 3477-3477/com.github.zhoukekestar.myapplication V/InputMethodManager: START INPUT: com.android.internal.policy.impl.PhoneWindow$DecorView{2421cef3 V.E..... R.....ID 0,0-1080,1920} ic=null tba=android.view.inputmethod.EditorInfo@2ea8435b controlFlags=#104
10-21 15:04:49.721 3477-3477/com.github.zhoukekestar.myapplication D/ColorDrawable: Color = -1118482, canvas = android.view.GLES20RecordingCanvas@158c97f8, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@23c03edc
10-21 15:04:49.722 3477-3477/com.github.zhoukekestar.myapplication D/ColorDrawable: Color = -12627531, canvas = android.view.GLES20RecordingCanvas@18e19b36, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@25b6a85f
10-21 15:04:49.723 3477-3477/com.github.zhoukekestar.myapplication D/ColorDrawable: Color = -13615201, canvas = android.view.GLES20RecordingCanvas@171dba37, mTintMode = SRC_IN, mTint = null, ColorDrawable = android.graphics.drawable.ColorDrawable@31661e5e
10-21 15:04:49.728 3477-3518/com.github.zhoukekestar.myapplication E/libEGL: cache file failed CRC check
10-21 15:04:49.824 3477-3518/com.github.zhoukekestar.myapplication D/IMGSRV: gralloc_register_buffer:1390: hnd=0x55b6f3a830 ID=3451657 fd=62 ref=1
10-21 15:04:49.824 3477-3518/com.github.zhoukekestar.myapplication D/GraphicBuffer: register, handle(0x55b6f3a830) (w:960 h:171 s:960 f:0x1 u:0x000b00)
10-21 15:04:49.850 3477-3518/com.github.zhoukekestar.myapplication V/RenderScript: 0x55b6f292a0 Launching thread(s), CPUs 3
10-21 15:04:53.118 3477-3518/com.github.zhoukekestar.myapplication D/OpenGLRenderer: Flushing caches (mode 0)
10-21 15:04:53.118 3477-3518/com.github.zhoukekestar.myapplication D/OpenGLRenderer: Flushing caches (mode 0)
10-21 15:04:53.120 3477-3518/com.github.zhoukekestar.myapplication D/GraphicBuffer: unregister, handle(0x55b6f3a830) (w:960 h:171 s:960 f:0x1 u:0x000b00)
10-21 15:04:53.120 3477-3518/com.github.zhoukekestar.myapplication D/IMGSRV: gralloc_unregister_buffer:1503: ID=3451657 ref=0

```

After removing `compile 'com.facebook.fresco:fresco:0.10.0'`, Error disappeared.
