### ISSUE TITLE
app start error

### ISSUE THREAD

**Issue by spiritelf** [zhoukekestar/weex-quick-start#5]
-20 11:25:44.316    1910-1910/com.github.zhoukekestar.weexquickstart E/weex﹕ launchInspector HackAssertionException com.taobao.weex.utils.WXHack$HackDeclaration$HackAssertionException: java.lang.ClassNotFoundException: com.taobao.weex.devtools.debug.DebugServerProxy
            at com.taobao.weex.utils.WXHack.into(WXHack.java:232)
            at com.taobao.weex.bridge.WXBridgeManager.launchInspector(WXBridgeManager.java:359)
            at com.taobao.weex.bridge.WXBridgeManager.<init>(WXBridgeManager.java:334)
            at com.taobao.weex.bridge.WXBridgeManager.getInstance(WXBridgeManager.java:346)
            at com.taobao.weex.WXSDKEngine.doInitInternal(WXSDKEngine.java:222)
            at com.taobao.weex.WXSDKEngine.initialize(WXSDKEngine.java:211)
            at com.github.zhoukekestar.weexquickstart.MainApplication.onCreate(MainApplication.java:18)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by zhoukekestar** [comment]
@spiritelf 等一下，我把我的所有环境做一下声明，以免产生不必要的错误。

**Comment by zhoukekestar** [comment]
你可以先[下载一下apk到你手机](https://github.com/zhoukekestar/weex-quick-start/releases/download/1.0.1/WeexQuickStart.apk)先试试能不能运行，不能运行的话，可能是手机兼容问题，如果可以的话，再找找本地编译环境的问题。我重新运行了我的项目，可以看一下我的[日志](https://github.com/zhoukekestar/weex-quick-start/blob/master/cmds.md)

**Comment by spiritelf** [comment]
之前一直报错 我把 classpath 'com.android.tools.build:gradle:2.0.0' 改成2.0.0才可以 不知道为什么

**Comment by spiritelf** [comment]
后来可以正常运行，但是会报这个错

11-21 17:45:19.287    1909-1909/com.github.zhoukekestar.weexquickstart E/weex﹕ launchInspector HackAssertionException com.taobao.weex.utils.WXHack$HackDeclaration$HackAssertionException: java.lang.ClassNotFoundException: com.taobao.weex.devtools.debug.DebugServerProxy
            at com.taobao.weex.utils.WXHack.into(WXHack.java:232)
            at com.taobao.weex.bridge.WXBridgeManager.launchInspector(WXBridgeManager.java:359)
            at com.taobao.weex.bridge.WXBridgeManager.<init>(WXBridgeManager.java:334)
            at com.taobao.weex.bridge.WXBridgeManager.getInstance(WXBridgeManager.java:346)
            at com.taobao.weex.WXSDKEngine.doInitInternal(WXSDKEngine.java:222)
            at com.taobao.weex.WXSDKEngine.initialize(WXSDKEngine.java:211)
            at com.github.zhoukekestar.weexquickstart.MainApplication.onCreate(MainApplication.java:18)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.ClassNotFoundException: com.taobao.weex.devtools.debug.DebugServerProxy
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:308)
            at java.lang.Class.forName(Class.java:272)
            at com.taobao.weex.utils.WXHack.into(WXHack.java:230)
            at com.taobao.weex.bridge.WXBridgeManager.launchInspector(WXBridgeManager.java:359)
            at com.taobao.weex.bridge.WXBridgeManager.<init>(WXBridgeManager.java:334)
            at com.taobao.weex.bridge.WXBridgeManager.getInstance(WXBridgeManager.java:346)
            at com.taobao.weex.WXSDKEngine.doInitInternal(WXSDKEngine.java:222)
            at com.taobao.weex.WXSDKEngine.initialize(WXSDKEngine.java:211)
            at com.github.zhoukekestar.weexquickstart.MainApplication.onCreate(MainApplication.java:18)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.taobao.weex.devtools.debug.DebugServerProxy" on path: DexPathList[[zip file "/data/app/com.github.zhoukekestar.weexquickstart-1/base.apk"],nativeLibraryDirectories=[/data/app/com.github.zhoukekestar.weexquickstart-1/lib/x86, /vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:308)
            at java.lang.Class.forName(Class.java:272)
            at com.taobao.weex.utils.WXHack.into(WXHack.java:230)
            at com.taobao.weex.bridge.WXBridgeManager.launchInspector(WXBridgeManager.java:359)
            at com.taobao.weex.bridge.WXBridgeManager.<init>(WXBridgeManager.java:334)
            at com.taobao.weex.bridge.WXBridgeManager.getInstance(WXBridgeManager.java:346)
            at com.taobao.weex.WXSDKEngine.doInitInternal(WXSDKEngine.java:222)
            at com.taobao.weex.WXSDKEngine.initialize(WXSDKEngine.java:211)
            at com.github.zhoukekestar.weexquickstart.MainApplication.onCreate(MainApplication.java:18)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
    Suppressed: java.lang.ClassNotFoundException: com.taobao.weex.devtools.debug.DebugServerProxy
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 22 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by zhoukekestar** [comment]
能跑起来就好，^^。

这个应该是没有引入devtools包引起的，不过应该不影响普通的页面展示，可以看看[这篇文章](http://alibaba.github.io/weex/doc/tools/devtools-android.html)，其实我是web前端开发人员，所以，还没有深入了解android-debug，这个项目只是先入个门，接下来的需要你自己去摸索咯。

**Comment by spiritelf** [comment]
前端工程师？

**Comment by zhoukekestar** [comment]
ios, android, web应该都算前端，可以都叫前端工程师，我是Web前端工程师

**Comment by spiritelf** [comment]
俗称可以把美工做的图 切成前端html js页面？

**Comment by spiritelf** [comment]
walk（） 你里面这个函数是做什么的？

**Comment by spiritelf** [comment]
webpack --watch & serve -p 8080"     这个命令好像不好使

**Comment by zhoukekestar** [comment]
`walk`函数是遍历`src`文件夹下的所有文件，监听文件变动，动态将`we`文件编译成`js`文件。
你也可以直接点击`weex\src\run.cmd`
```bash
D:\Github\weex-quick-start\weex>npm run build

> weex-quick-start@0.4.0 build D:\Github\weex-quick-start\weex
> webpack --watch --config ./webpack.config.js

Hash: f00bac41ed9a6fa81d64
Version: webpack 1.13.1
Time: 300ms
                                                       Asset     Size  Chunks             Chunk Names
                        ..\app\src\main\assets\weex\index.js  2.23 kB       0  [emitted]  ..\app\src\main\assets\weex\index
..\app\src\main\assets\weex\weex_tmp\h5_render\demo\index.js  2.84 kB       1  [emitted]  ..\app\src\main\assets\weex\weex_tmp\h5_render\demo\index
    + 2 hidden modules
```

至于`webpack --watch & serve -p 8080`命令，由于是windows系统，建议你在weex目录下先执行`webpack --watch`，然后新开一个终端，执行`serve -p 8080`，执行`serve`命令的前提是安装了`serve`，可通过`npm install serve -g`安装

**Comment by spiritelf** [comment]
问下 如果用vue写的项目 可以编到这里面app吗？

**Comment by zhoukekestar** [comment]
这个，虽然weex基于vue，还是需要修改的，比如，document，window对象的差异。组件化的话，[vue](http://vuejs.org/v2/guide/single-file-components.html)和weex还是有些差别，还有关于CSS，vue基于browser可以完全支持，但weex就仅支持css子集。总的来说，业务逻辑代码可以复用，与框架相关代码，需要重写。具体的话，还是需要你自己去尝试。

**Comment by spiritelf** [comment]
有没有遇到 weex debug 模式调试。。路径问题啊？

**Comment by zhoukekestar** [comment]
暂时没有进行这方面的尝试，最近公司事情比较多，建议你去[官网issues](https://github.com/alibaba/weex/issues)提问题，或者进[gitter](https://gitter.im/weexteam/cn)讨论， 或者搜索相关的QQ群进行询问。不好意思，帮不到你了。
